### ISSUE TITLE
Uses about 3x as much memory when saving maps

### ISSUE THREAD

**Issue by ymd-stella** [stella-cv/stella_vslam#215]
The memory overhead of nlohmann/json is large.

ref. https://github.com/nlohmann/json/issues/1613

Consider a different storage format.

- [FlatBuffers](https://google.github.io/flatbuffers/)
- [SQLite](https://www.sqlite.org/index.html)

**Comment by ThibaudM** [comment]
SQLite is really a good alternative. It is a little bit verbose but is very very fast (more than 3x) if you store the main data as blobs (descriptors, kps, map points...). _DB Browser for SQLite_ is a good tool to visualize data quickly.

Disclaimer: at Wemap, in our internal SLAM project we use SQLite to save / load / prepare and merge datasets.
