### ISSUE TITLE
Invalid setup type: Stereo

### ISSUE THREAD

**Issue by DrorSegev** [stella-cv/stella_vslam#282]
When running any stereo configuration like:

./run_video_slam -v ./orb_vocab.fbow -m ./out.mp4 -c ../example/euroc/EuRoC_stereo.yaml --frame-skip 1  --auto-term --eval-log --map-db map3.msg --debug 

I'm getting the error:
Error:
Invalid setup type: Stereo

Thanks
Drrror

**Comment by ymd-stella** [comment]
Wrong file.
See https://github.com/stella-cv/stella_vslam/blob/main/example/euroc/EuRoC_stereo.yaml#L10.
