### ISSUE TITLE
Preprocessing::min_size does not have hard or soft upper limit on no of ORB Features to extract

### ISSUE THREAD

**Issue by mitul93** [stella-cv/stella_vslam#307]
I saw in #299 that ORB extraction now uses resolution independent parameter (min_size).
During the test from v0.3.3, I noticed slow run-time. 

I think that's because there is no upper bound of number of features to extract.
Can someone confirm this?

**Comment by ymd-stella** [comment]
> Preprocessing::min_size does not have hard or soft upper limit on no of ORB Features to extract

There is an upper limit to the number of feature points. The upper limit is the number of regions when the region division is repeated until the size reaches min_size.

**Comment by ymd-stella** [comment]
I know that speeds may decrease under certain conditions. Please let us know your benchmarking conditions and results.

**Comment by ymd-stella** [comment]
In fact, (if the appropriate value is set for min_size,) https://github.com/stella-cv/stella_vslam/pull/299 only changes the processing time for feature extraction by a few milliseconds, and the largest change in processing time is for pose optimization. For a fundamental solution, I think it is necessary to put an upper limit on the processing time for pose optimization.
