### ISSUE TITLE
Blank Screen in Pangolin Viewer

### ISSUE THREAD

**Issue by zovelsanj** [stella-cv/stella_vslam#314]
## Problem Encountered
When trying to visualize the equirectangular dataset output, Pangolin Viewer (in both Frame Viewer and Map Viewer) is blank. I followed exactly the same steps for [installation](https://stella-cv.readthedocs.io/en/latest/installation.html) and [visualization](https://stella-cv.readthedocs.io/en/latest/simple_tutorial.html) as described in stella_vslam documentation. Building process is error free for all dependencies and the source as well.
![Screenshot from 2022-05-30 13-47-22](https://user-images.githubusercontent.com/37138338/170946902-0689fd4c-7a94-4f8d-8cec-7e6b7d7e1be5.png)

When running the sample plots (`Pangolin/examples/SamplePlot/main.cpp`) of Pangolin the output is visible and perfect like this:
![Screenshot from 2022-05-30 10-55-16](https://user-images.githubusercontent.com/37138338/170947427-23e0c85d-5fe6-4e59-8d7a-f694c3c05515.png)

It seems Pangolin has problem showing output with just stella_vslam. The Pangolin i built was as suggested in the stella_vslam documentaion (from commit ID [ad8b5f8](https://github.com/stevenlovegrove/Pangolin/tree/ad8b5f83222291c51b4800d5a5873b0e90a0cf81).). 

## Environment
- OS: Ubuntu 20.04
- Install procedure: exactly as described in [stella_vslam documentation](https://stella-cv.readthedocs.io/en/latest/installation.html)
- dataset: aist_living_lab_1 (as given in [Simple Tutorial](https://stella-cv.readthedocs.io/en/latest/simple_tutorial.html) of stella_vslam documention, I checked the video inside aist_living_lab_1 directory it plays completely fine.) 

## Additional context
There is also no problem with opengl, its dependencies and graphics drivers.

Can anyone help me with this?

**Comment by ymd-stella** [comment]
Try 

```shell
$ export LIBGL_ALWAYS_SOFTWARE=1
```

**Comment by ymd-stella** [comment]
The visualizer in the attached image appears to be normal. It seems to be loading an invalid map and doing localization.

**Comment by ymd-stella** [comment]
@zovelsanj If you still have questions, please ask them in discussions.
