### ISSUE TITLE
Documenting conventions

### ISSUE THREAD

**Issue by ali-sx** [stella-cv/stella_vslam#321]
I've been using openvslam/stella_vslam for some time and I find it really difficult to find info about the conventions used (what is the ordering of the bearing vectors ? how is the axes oriented ? etc.).

Is there a place where all these informations are centralized ?

If not, I think it could really help new contributors and speed up their onboarding. Maybe by using a wiki that everyone can update.

**Comment by ymd-stella** [comment]
Documentation is open source. See https://github.com/stella-cv/docs.
