### ISSUE TITLE
Expose 'tracking_module.cc::feed_frame()'-parameter 'init_retry_thr' to 'conf'-class

### ISSUE THREAD

**Issue by McC0dy** [stella-cv/stella_vslam#322]
## What issue is the feature request related to?

The system resets if it looses tracking shortly after initialization - this is reasonable behavior. 
However, currently the threshold is hard-coded to 5 sec but this value does not fit all applications (mine included),

## Describe the solution you'd like

Expose `init_retry_thr` from `tracking_module::feed_frame()`.

### How to achieve this

(Includes @ymd-stella's comment below. Thanks)
- [ ] In `tracking_module.h/.cc`: Through the `tracking_module` constructor expose `init_retry_thr` and set the default value to `5.0`. See: https://github.com/stella-cv/stella_vslam/blob/3f4b160e4eb065cf9a800160e9b38887658cd58f/src/stella_vslam/tracking_module.h#L114-L122 and https://github.com/stella-cv/stella_vslam/blob/3f4b160e4eb065cf9a800160e9b38887658cd58f/src/stella_vslam/tracking_module.cc#L24-L27
- [ ] In docs "Parameter"-section: Add variable `init_retry_thr` and a fitting description. See https://github.com/stella-cv/docs/blob/9cb9458c9ea9e49d8feaa71c278f9872f76a2588/docs/parameters.rst?plain=1#L101-L117

## Describe alternatives you've considered

Changing the video metadata FPS would allow for indirectly affecting the threshold but could have unintentional consequences.

**Comment by ymd-stella** [comment]
> In conf.h/.cc: Add parameter init_retry_thr

Not required.

> In tracking_module.h/.cc: Through the tracking_module constructor expose init_retry_thr

See 
https://github.com/stella-cv/stella_vslam/blob/3f4b160e4eb065cf9a800160e9b38887658cd58f/src/stella_vslam/tracking_module.h#L114-L122

> In stella-cv/examples: Update all yaml files to include init_retry_thr: 5.0

Set the default value to 5.0.

See https://github.com/stella-cv/stella_vslam/blob/3f4b160e4eb065cf9a800160e9b38887658cd58f/src/stella_vslam/tracking_module.cc#L24-L27

> Update documentation accordingly

See 
https://github.com/stella-cv/docs/blob/9cb9458c9ea9e49d8feaa71c278f9872f76a2588/docs/parameters.rst?plain=1#L101-L117

**Comment by McC0dy** [comment]
@ymd-stella I've included your feedback in the original description. Thank you.
Did I understand correctly that it's not needed to add `init_retry_thr: 5.0` to the example yaml's?
