### ISSUE TITLE
pass by reference in loop variables

### ISSUE THREAD

**Issue by mitul93** [stella-cv/stella_vslam#371]
## Describe the bug
following variables should pass by reference to avoid unnecessary copy

https://github.com/stella-cv/stella_vslam/blob/a404f57c1999d8e29475b490e5fe26c38469df53/src/stella_vslam/data/keyframe.cc#L326

https://github.com/stella-cv/stella_vslam/blob/a404f57c1999d8e29475b490e5fe26c38469df53/src/stella_vslam/data/map_database.cc#L196

https://github.com/stella-cv/stella_vslam/blob/a404f57c1999d8e29475b490e5fe26c38469df53/src/stella_vslam/io/map_database_io_sqlite3.cc#L71

https://github.com/stella-cv/stella_vslam/blob/a404f57c1999d8e29475b490e5fe26c38469df53/src/socket_publisher/data_serializer.cc#L93

https://github.com/stella-cv/stella_vslam/blob/a404f57c1999d8e29475b490e5fe26c38469df53/src/socket_publisher/data_serializer.cc#L146

https://github.com/stella-cv/stella_vslam/blob/a404f57c1999d8e29475b490e5fe26c38469df53/src/socket_publisher/data_serializer.cc#L169

https://github.com/stella-cv/stella_vslam/blob/a404f57c1999d8e29475b490e5fe26c38469df53/src/socket_publisher/data_serializer.cc#L136

## Solution
Use loop variable by reference 
```
for (const auto &id_marker : markers_) {
        markers.push_back(id_marker.second);
    }
```
Repeat this for all lines mentioned above

## Expected behavior
Not Applicable

## Screenshots or videos
Not Applicable

## Environment

- Hardware: PC
- CPU: i7-12700
- OS: Ubuntu 22.04
- Commit id: a404f57c1999d8e29475b490e5fe26c38469df53

**Comment by jacobjohnso** [comment]
Hi, I would like to have a go at resolving this issue. Could you assign it to me?

**Comment by annavordou** [comment]
Hello, is this issue still open?
