### ISSUE TITLE
OpenMP requires signed integral type as index variables

### ISSUE THREAD

**Issue by SteffenEhrle** [stella-cv/stella_vslam#394]
## Compile error: index Variable in OpenMP 'for' statement must have signed integral type
Using 'unsigned int' in openmp accelerated for-loops leads to compile errors with certain versions of OpenMP. 

## To Reproduce
Compile under Windows using OpenMP (USE_OPENMP):
"error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type"

## Environment

- Hardware: [PC]
- CPU: [Intel Core i7]
- OS: [Windows 10]
- Commit id: [master]

## Solution
Exchange unsigned int with int64_t in affected for-loops?

**Comment by ymd-stella** [comment]
Why can't you use the new version of OpenMP?

**Comment by SteffenEhrle** [comment]
I am locked to this version of omp because of other libraries included via vcpkg.
