### ISSUE TITLE
complier error in data/graph_node.cc

### ISSUE THREAD

**Issue by AlexWan1027** [stella-cv/stella_vslam#425]
## Describe the bug

complier error report in ubuntu16.04
stella_vslam/data/graph_node.cc:106:50:  error: use of ‘keyfrm_and_num_shared_lms’ before deduction of ‘auto’
     for (const auto& keyfrm_and_num_shared_lms : keyfrm_and_num_shared_lms) {

This code should be 'for (const auto& keyfrm_and_num_shared_lm : keyfrm_and_num_shared_lms)', not 'for (const auto& keyfrm_and_num_shared_lms : keyfrm_and_num_shared_lms)'?

**Comment by ymd-stella** [comment]
Use Ubuntu 18.04 or later.

**Comment by ymd-stella** [comment]
Renamed the variable name.

I don't intend to check if it works on Ubuntu 16.04, but it might.
