### ISSUE TITLE
Optional Mapping configuration

### ISSUE THREAD

**Issue by AlejandroSilvestri** [stella-cv/stella_vslam#531]
As for version 0.4.0, all configuration parameters except for Camera node have default values, leading to much smaller configuration files.  But stella_vslam fails to run if you entirely omit the Mapping node in yaml file.
It works if you just add "Mapping:", without any actual mapping configuration.
It's a very minimal bug.
This is the line causing the error:
 https://github.com/stella-cv/stella_vslam/blob/a18add795ecbf2506bf9b1749ff688e7093aef74/src/stella_vslam/system.cc#L66 

I believe it can be fixed by changing the first argument for:

    mapper_ = new mapping_module(util::yaml_optional_ref(cfg_->yaml_node_, "Mapping"), map_db_, bow_db_, bow_vocab_);

Not tested, I am sorry I don't pull a request.

**Comment by Skwangles** [comment]
@ymd-stella Close this issue
